### ISSUE TITLE
conky.conf文件中文字乱码？

### ISSUE THREAD

**Issue by amazingfate** [zhengfaxiang/dotfiles#1]
在浏览器上浏览github的代码是乱码，下载到本地用notepad++编辑换了编码仍然还是乱码

**Comment by fzh3g** [comment]
> 在浏览器上浏览github的代码是乱码，下载到本地用notepad++编辑换了编码仍然还是乱码

Perhaps you need to install [FontAwesome](https://github.com/FortAwesome/Font-Awesome/tree/master/fonts). `FontAwesome.otf` is enough.

**Comment by Arthurwu24** [comment]
How to make conky transparent just like your screenshot.png  shows?   I have set "background yes", but it didn't work ...

**Comment by fzh3g** [comment]
> How to make conky transparent just like your screenshot.png shows?

I use a third party package `compton` and set the opacity in my `.compton.conf`:

```
wintypes:
{
  dock = { opacity = 0.72; };
};
```

for more details, please refer to [my .compton.conf](https://github.com/zhengfaxiang/dotfiles/blob/master/compton/.compton.conf).
